name: Build Android Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies (FORÇANDO instalação do FFmpeg)
        # CORREÇÃO CRÍTICA: Adicionar --force para resolver conflito de dependências do FFmpeg
        run: npm install --force

      - name: Build Web Assets (Cria a pasta www)
        run: npm run build
        
      # === CORREÇÃO CRÍTICA DO ERRO ===
      # Esta etapa remove a pasta 'android/' para que 'npx cap add android' possa ser executado
      - name: Remover Artefato Antigo (Limpeza)
        run: rm -rf android/
      
      - name: Add Android Platform
        run: npx cap add android

      - name: Initialize Capacitor and Sync
        run: npx cap sync android

      - name: Set Permissions for Gradle Wrapper
        run: chmod +x android/gradlew

      - name: Build Android Debug APK
        run: ./gradlew assembleDebug
        working-directory: ./android

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

